BEGIN:VCARD
VERSION:2.1
N;CHARSET=utf-8;ENCODING=QUOTED-PRINTABLE:<!--Name-->;<!--Firstname-->
FN;CHARSET=utf-8;ENCODING=QUOTED-PRINTABLE:<!--Name--> <!--Firstname-->
ORG;CHARSET=utf-8;ENCODING=QUOTED-PRINTABLE:<!--Company-->
NOTE;CHARSET=utf-8;ENCODING=QUOTED-PRINTABLE:<!--Comments-->
TEL;WORK;VOICE;CHARSET=utf-8;ENCODING=QUOTED-PRINTABLE:<!--Phone-->
TEL;WORK;FAX;CHARSET=utf-8;ENCODING=QUOTED-PRINTABLE:<!--Fax-->
ADR;WORK;CHARSET=utf-8;ENCODING=QUOTED-PRINTABLE:;;<!--Street-->;<!--City-->;;<!--ZIP-->;<!--Country-->
URL;WORK;CHARSET=utf-8;ENCODING=QUOTED-PRINTABLE:<!--URL-->
LANGUAGES;ENCODING=QUOTED-PRINTABLE:<!--Languages-->
EMAIL;PREF;INTERNET:<!--Email-->
X-WAB-GENDER:<!--Gender-->
<!--Picture-->

REV:20100526T083502Z
END:VCARD