theme: jekyll-theme-minimal
show_downloads: [true]
google_analytics: [G-C2BQJTPHV6]
title: LiveZilla Server
description: LiveZilla includes a live chat software with multi-website support, visitor monitoring and a help desk system that allows you to not only integrate emails that you receive from customers but also messages from Twitter and Facebook in your ticket system.
logo: https://user-images.githubusercontent.com/61565955/159957196-b9a858f9-ae76-4d01-92c5-3808ec7bc01e.png